.PHONY: clean All

All:
	@echo "----------Building project:[ Arqueiro - Debug ]----------"
	@cd "Arqueiro" && "$(MAKE)" -f  "Arqueiro.mk"
clean:
	@echo "----------Cleaning project:[ Arqueiro - Debug ]----------"
	@cd "Arqueiro" && "$(MAKE)" -f  "Arqueiro.mk" clean
